//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseTracker.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense not added.
        /// </summary>
        internal static string AddExpenseFailed {
            get {
                return ResourceManager.GetString("AddExpenseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense added successfully.
        /// </summary>
        internal static string AddExpenseSuccess {
            get {
                return ResourceManager.GetString("AddExpenseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income not added.
        /// </summary>
        internal static string AddIncomeFailed {
            get {
                return ResourceManager.GetString("AddIncomeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income added successfully.
        /// </summary>
        internal static string AddIncomeSuccess {
            get {
                return ResourceManager.GetString("AddIncomeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Add income
        ///2.Add expense
        /// Enter your choice.
        /// </summary>
        internal static string AddMenu {
            get {
                return ResourceManager.GetString("AddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Enter your own date in (YYYY/MM/DD) format 
        ///2. Todays date.
        /// </summary>
        internal static string DateMenu {
            get {
                return ResourceManager.GetString("DateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your option.
        /// </summary>
        internal static string DateOption {
            get {
                return ResourceManager.GetString("DateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid choice.
        /// </summary>
        internal static string DefaultMessage {
            get {
                return ResourceManager.GetString("DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Delete income
        ///2.Delete expense 
        ///Enter your choice.
        /// </summary>
        internal static string DeleteMenu {
            get {
                return ResourceManager.GetString("DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Edit income
        ///2.Edit expense
        ///Enter your choice.
        /// </summary>
        internal static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter expense Category .
        /// </summary>
        internal static string EnterExpenseCategory {
            get {
                return ResourceManager.GetString("EnterExpenseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter income source.
        /// </summary>
        internal static string EnterIncomeSource {
            get {
                return ResourceManager.GetString("EnterIncomeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No expense added yet.
        /// </summary>
        internal static string ExpenseEmpty {
            get {
                return ResourceManager.GetString("ExpenseEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No incomes added yet.
        /// </summary>
        internal static string IncomeEmpty {
            get {
                return ResourceManager.GetString("IncomeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid amount.
        /// </summary>
        internal static string InvalidAmount {
            get {
                return ResourceManager.GetString("InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid category.
        /// </summary>
        internal static string InvalidCategory {
            get {
                return ResourceManager.GetString("InvalidCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number.
        /// </summary>
        internal static string InvalidChoice {
            get {
                return ResourceManager.GetString("InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid date.
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID should be in the format I1 for income and E1 for the expense.
        /// </summary>
        internal static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source.
        /// </summary>
        internal static string InvalidSource {
            get {
                return ResourceManager.GetString("InvalidSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Add income/expense 
        ///2.Edit income/expense
        ///3.Delete income/expense
        ///4.View income/expense
        ///5.Get Summary
        ///6.Exit
        ///Enter your Choice.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes made.
        /// </summary>
        internal static string NoChanges {
            get {
                return ResourceManager.GetString("NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching expense found
        ///Couldn&apos;t update the expense.
        /// </summary>
        internal static string NoExpenseFound {
            get {
                return ResourceManager.GetString("NoExpenseFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching income found
        ///Couldn&apos;t update the income.
        /// </summary>
        internal static string NoIncomeFound {
            get {
                return ResourceManager.GetString("NoIncomeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transactions made yet.
        /// </summary>
        internal static string TransactionEmpty {
            get {
                return ResourceManager.GetString("TransactionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense updated successfully.
        /// </summary>
        internal static string UpdateExpenseSuccess {
            get {
                return ResourceManager.GetString("UpdateExpenseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income updated successfully.
        /// </summary>
        internal static string UpdateIncomeSuccess {
            get {
                return ResourceManager.GetString("UpdateIncomeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.View income
        ///2.View expense 
        ///Enter your choice.
        /// </summary>
        internal static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
    }
}
